### ISSUE TITLE
Map displays a custom cursor and animations

### ISSUE THREAD

**Issue by BethProjects85** [districtr/districtr-mapbox-gl#28]
Adds a cursor component to the map. It should deactivate when the mouse leaves the map. 

```[tasklist]
### Tasks
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/40
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/39
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/38
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/37
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/36
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/35
```
