### ISSUE TITLE
Select brush colors from Color Picker component

### ISSUE THREAD

**Issue by grandrepublic** [districtr/districtr-mapbox-gl#41]
Users can use a color picker to change the brush color

```[tasklist]
### Tasks
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/42
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/43
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/44
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/45
- [ ] https://github.com/districtr/districtr-mapbox-gl/issues/46
```
