### ISSUE TITLE
Toolbars can be configured

### ISSUE THREAD

**Issue by grandrepublic** [districtr/districtr-mapbox-gl#51]
Maps will have a tool bar on each side of the page. Each toolbar has a top middle and bottom area for holding tools. Tools are configured by describing the tool and the inputs, widgets, and panels that control the tool properties. 

```[tasklist]
### Tasks
- [ ] Toolbar component can set to the left or right of the page.
- [ ] Toolbars have a top, middle, and bottom section which holds tools.
- [ ] Toolbar responded to users preference for light or dark mode. 
```
